en:
  title: PlatyPS
  description: >-
    Write PowerShell External Help in Markdown.
  languageName: English
  weight: 1
# Example additional language support for Farsi
# fa:
#   title: اسناد گلدی
#   description: یک نمونه برای پوسته داکسی
#   languageName: فارسی
#   contentDir: content/fa
#   time_format_default: 2006.01.02
#   time_format_blog: 2006.01.02
